# Medication Dosage Monitor Exercises

Based on what you have learnt so far, these are three exercises with a medication dosage monitoring scenario. Each exercise processes patient data (name, age, weight, and dosage records with time and dose in mg) and applies weight-based and age-based safe dose ranges. The safe dose range is:
- **Adults (age ≥ 18)**: 0.1–0.5 mg/kg
- **Pediatrics (age < 18)**: 0.05–0.3 mg/kg

The exercises increase in difficulty, building on each other with validation, alerts, averages, risk assessment, and exception handling.


NOTE: Only Exercise 1 is considered as graded assignment. The other two are the materials for the upcoming session. 

## Exercise 1: Basic Dosage Safety Check for Multiple Patients

**Problem**: Validate medication dosages for multiple patients. Each patient has a name, age, weight (kg), and a list of dosage records (time, dose in mg). The program should:
- Calculate the safe dose range based on age and weight.
- Check if each dose is Safe (within range), Unsafe (outside range), or Invalid (≤ 0).
- Print each patient’s dosage status and the total number of valid doses.

**Sample Input**:
```python
patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': -5}
        ]
    }
]
```

**Expected Output**:
```
Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  Total valid doses: 2
Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  Invalid dose at 12:00: Dose must be positive.
  Total valid doses: 1
```

In [2]:
patients = [
    {
        'name': 'Alice',
        'age': 30,
        'weight': 60,
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40}
        ]
    },
    {
        'name': 'Bob',
        'age': 16,
        'weight': 40,
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': -5}
        ]
    }
]

for patient in patients:
    name = patient['name']
    age = patient['age']
    weight = patient['weight']
    dosages = patient['dosages']


    if age >= 18:
        min_dose = 0.1 * weight
        max_dose = 0.5 * weight
    else:
        min_dose = 0.05 * weight
        max_dose = 0.3 * weight

    print(f"{name} (Age: {age}, Weight: {weight} kg, Safe Range: {round(min_dose,1)}–{round(max_dose,1)} mg):")
    valid_doses = 0

    for item in dosages:
        time = item['time']
        dose = item['dose']

        if dose <= 0:
            print(f" {time}: Invalid dose at {time}: Dose must be positive.")
            continue

        valid_doses += 1
        if min_dose <= dose <= max_dose:
            status = "Safe"
        else:
            status = "Unsafe"
        print(f" {time}: Dose={dose} mg - {status}")

    print(f" Total valid doses: {valid_doses}\n")


Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
 08:00: Dose=10 mg - Safe
 12:00: Dose=40 mg - Unsafe
 Total valid doses: 2

Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
 08:00: Dose=5 mg - Safe
 12:00: Invalid dose at 12:00: Dose must be positive.
 Total valid doses: 1



## Exercise 2: Dosage Alerts and Average Calculation with Age-Based Rules

**Problem**: Extend the program to issue alerts for unsafe doses and calculate the average dose per patient. The program should:
- Calculate the safe dose range (0.1–0.5 mg/kg for age ≥ 18; 0.05–0.3 mg/kg for age < 18).
- Validate doses: Safe, Unsafe, or Invalid (≤ 0).
- Store times of unsafe doses for alerts.
- Calculate the average dose for valid doses per patient.
- Print each patient’s dosage status, unsafe dose alerts, and average dose.

**Sample Input**:
```python
patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40},
            {'time': '16:00', 'dose': 15}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': 15}
        ]
    }
]
```

**Expected Output**:
```
Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  16:00: Dose=15 mg - Safe
  Alert: Unsafe dose detected at 12:00
  Average dose: 21.7 mg
Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  12:00: Dose=15 mg - Unsafe
  Alert: Unsafe dose detected at 12:00
  Average dose: 10.0 mg
```

In [1]:

patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40},
            {'time': '16:00', 'dose': 15}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': 15}
        ]
    }
]

for patient in patients:
    Name=patient['name']
    Age=patient['age']
    Weight=patient['weight']


    if patient['age']>=18:
        min_dose=0.1*patient['weight']
        max_dose=0.5*patient['weight']
    else:
        min_dose=0.05*patient['weight']
        max_dose=0.3*patient['weight']
    print(f"{Name} (Age:{Age} , Weight:{Weight} kg , Safe Range : {round(min_dose,1)}-{round(max_dose,1)} mg)")

    doses=patient['dosages']

    for items in doses:
        Time=items['time']
        Dose=items['dose']


        if min_dose<Dose<max_dose:
            status='Safe'
        else:
            status='Unsafe'
        print(f"{Time}: Dose:{Dose} - {status}")
        
        if Dose>max_dose:
            print(f"Alert : unsafe dose detected at {Time}")
            continue




        
    a=[]
    for items in doses:
        dose=float(items['dose'])
        a.append(dose)
        average=sum(a)/len(a)
    print(f"Average dose: {round(average,1)} mg")

Alice (Age:30 , Weight:60 kg , Safe Range : 6.0-30.0 mg)
08:00: Dose:10 - Safe
12:00: Dose:40 - Unsafe
Alert : unsafe dose detected at 12:00
16:00: Dose:15 - Safe
Average dose: 21.7 mg
Bob (Age:16 , Weight:40 kg , Safe Range : 2.0-12.0 mg)
08:00: Dose:5 - Safe
12:00: Dose:15 - Unsafe
Alert : unsafe dose detected at 12:00
Average dose: 10.0 mg


## Exercise 3: Dosage Risk Assessment and Distribution with Exception Handling

**Problem**: Extend the program to assess patient risk, analyze dosage status distribution, and handle exceptions robustly. The program should:
- Calculate the safe dose range (0.1–0.5 mg/kg for age ≥ 18; 0.05–0.3 mg/kg for age < 18).
- Validate doses: Safe, Unsafe, or Invalid (≤ 0).
- Flag patients as 'High Risk' if they have 2 or more unsafe doses or if their average dose exceeds the safe range.
- Calculate the distribution of Safe and Unsafe doses (percentage of valid doses) per patient.
- Handle exceptions (e.g., missing keys, invalid data types).
- Print each patient’s dosage status, risk assessment, and distribution.

**Sample Input**:
```python
patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40},
            {'time': '16:00', 'dose': 35}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': 15},
            {'time': '16:00', 'dose': 'invalid'}
        ]
    }
]
```

**Expected Output**:
```
Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  16:00: Dose=35 mg - Unsafe
  Risk Status: High Risk (2 unsafe doses)
  Distribution: Safe: 1 (33.3%), Unsafe: 2 (66.7%)
Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  12:00: Dose=15 mg - Unsafe
  Error at 16:00: Invalid dose value (non-numeric).
  Risk Status: Low
  Distribution: Safe: 1 (50.0%), Unsafe: 1 (50.0%)
```

In [2]:

patients = [
    {
        'name': 'Alice', 
        'age': 30, 
        'weight': 60, 
        'dosages': [
            {'time': '08:00', 'dose': 10},
            {'time': '12:00', 'dose': 40},
            {'time': '16:00', 'dose': 35}
        ]
    },
    {
        'name': 'Bob', 
        'age': 16, 
        'weight': 40, 
        'dosages': [
            {'time': '08:00', 'dose': 5},
            {'time': '12:00', 'dose': 15},
            {'time': '16:00', 'dose': 'invalid'}
        ]
    }
]

for patient in patients:
    name = patient['name']
    age = patient['age']
    weight = patient['weight']
    dosages = patient['dosages']
    
    
    if age >= 18:
        min_safe = 0.1 * weight
        max_safe = 0.5 * weight
    else:
        min_safe = 0.05 * weight
        max_safe = 0.3 * weight
    
    print(f"{name} (Age: {age}, Weight: {weight} kg, Safe Range: {min_safe:.1f}–{max_safe:.1f} mg):")
    
    safe = 0
    unsafe = 0
    total_doses = 0
    total_mg = 0
    unsafe_times = []
    
    for items in dosages:
        time = items['time']
        dose = items['dose']
        
        
        if not isinstance(dose, (int, float)):
            print(f"  Error at {time}: Invalid dose value (non-numeric).")
            continue
        
        
        total_doses += 1
        total_mg += dose
        
        if min_safe <= dose <= max_safe:
            safe += 1
            status = "Safe"
        else:
            unsafe += 1
            status = "Unsafe"
            unsafe_times.append(time)
        
        print(f"  {time}: Dose={dose} mg - {status}")
    
    
    risk = "Low"
    if unsafe >= 2:
        risk = f"High Risk ({unsafe} unsafe doses)"
    elif total_doses > 0:
        avg_dose = total_mg / total_doses
        if avg_dose > max_safe:
            risk = f"High Risk (average dose {avg_dose:.1f} mg)"
    
    print(f"  Risk Status: {risk}")
    
    
    if total_doses > 0:
        safe_pct = (safe / total_doses) * 100
        unsafe_pct = (unsafe / total_doses) * 100
        print(f"  Distribution: Safe: {safe} ({safe_pct:.1f}%), Unsafe: {unsafe} ({unsafe_pct:.1f}%)")
    
    print() 

Alice (Age: 30, Weight: 60 kg, Safe Range: 6.0–30.0 mg):
  08:00: Dose=10 mg - Safe
  12:00: Dose=40 mg - Unsafe
  16:00: Dose=35 mg - Unsafe
  Risk Status: High Risk (2 unsafe doses)
  Distribution: Safe: 1 (33.3%), Unsafe: 2 (66.7%)

Bob (Age: 16, Weight: 40 kg, Safe Range: 2.0–12.0 mg):
  08:00: Dose=5 mg - Safe
  12:00: Dose=15 mg - Unsafe
  Error at 16:00: Invalid dose value (non-numeric).
  Risk Status: Low
  Distribution: Safe: 1 (50.0%), Unsafe: 1 (50.0%)

